spring:
  datasource:
    url: jdbc:sqlserver://10.0.2.15:1433;databaseName=meniga;IntegratedSecurity=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: admin

batch:
  outputFolder: /Users/frankzhang/eclipse-workspace/MenigaExtractor/outputFiles/
  sourceSystemCode: ADV
  countryCode: TH
  delimiter: "\u0007"
  
  



