spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=meniga
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: frank
    password: Frank123

batch:
  outputFolder: outputFiles/
  sourceSystemCode: ADV
  countryCode: TH
  delimiter: "\u0007"
  
  



